server:
    port: 80
    context-path: /
spring:
    datasource:
        url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false
        username: root
        password: root
        driver-class-name: com.mysql.jdbc.Driver
        platform: mysql
        type: com.alibaba.druid.pool.DruidDataSource
        initial-size: 1
        min-idle: 1
        max-active: 20
        test-on-borrow: true
    jpa:
      database: mysql
      show-sql: true
      hibernate:
        ddl-auto: update
    freemarker:
        cache: false
        request-context-attribute: request
    mail:
        host: smtp.qq.com
        username: 1007894493@qq.com
        password: # 如果是qq邮箱的话，这里要配置成授权码

